### ISSUE TITLE
Git Clone

### ISSUE THREAD

**Issue by frobulator** [0100Dev/WHMCS-Mollie#1]
Initialized empty Git repository in /var/www/klanten.networkoperations.nl/git-mollie-whmcs/src/mollie/vendor/Mollie/.git/ 

Fatal error: require_once() [function.require]: Failed opening required '/var/www/wwwdirl/wwwroot/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Autoloader.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/wwwdir
/wwwroot/modules/gateways/mollie/mollie.php on line 3

**Comment by Wouter0100** [comment]
Dit commando zou het moeten oplossen, hoor graag of het gewerkt heeft.
```
git clone --recursive https://github.com/0100Dev/WHMCS-Mollie.git /tmp/whmcs && sudo mv /tmp/whmcs/src /var/www/klanten.networkoperations.nl/wwwroot/modules/gateways/
```

**Comment by frobulator** [comment]
Helaas niet :(

Submodule 'src/mollie/vendor/Mollie' (git@github.com:mollie/mollie-api-php.git) registered for path 'src/mollie/vendor/Mollie'
Cloning into 'src/mollie/vendor/Mollie'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by Wouter0100** [comment]
Ah. Probeer even opnieuw. 0967f9bd06bdf71329e987d0592aba9f9d25ea95 zou het opgelost moeten hebben.

**Comment by frobulator** [comment]
Top... :) Doet het nu

**Comment by Wouter0100** [comment]
Fijn, goed te horen!
