### ISSUE TITLE
After upload configgateways.php is unreachable 

### ISSUE THREAD

**Issue by DoFox** [0100Dev/WHMCS-Mollie#10]
After a FTP and git upload the configgateways.php is unreachable. We still have to sort out the problem and why it won't work. Sadly I cannot restore a backup since I haven't got one.

**Comment by DoFox** [comment]
Error is found and will only happen when the standard iDEAL from WHMCS and Mollie is enabled. 

Works fine now!

**Comment by Wouter0100** [comment]
Good to hear, what was the exact error you've got? Maybe because both are named `mollieideal` or something.
