### ISSUE TITLE
callback.php kan niet aangeroepen worden

### ISSUE THREAD

**Issue by bgoedhart** [0100Dev/WHMCS-Mollie#14]
Hi,

Wij zijn bezig met de Mollie plugin te testen in WHMCS. De betaling zelf gaat goed, maar Mollie kan de callback.php niet bereiken. In de apache logfile zie je alleen maar een error 500. We komen er maar niet achter waarom callback.php niet bereikbaar is van buitenaf. Het bestand bestaat gewoon op de server. mollie.php is wel bereikbaar in dezelfde directory. We hebben geen .htaccess bestanden staan die het eventueel zouden kunnen verpesten. Enig idee, wat hier mis gaat?

**Comment by thehosting4you** [comment]
Goedemorgen,

Ik weet dat dit heeft te maken dat mollie verbinding wil maken met de callback.php via een bepaalde poort.
Alleen weet ik op dit moment niet meer welke dat is:-(

Met vriendelijk groet,
André

**Comment by bgoedhart** [comment]
Hoi André,

Maar dan zou ik het bestand toch zelf wel moeten kunnen aanroepen via HTTPS zonder een 500 error te krijgen?

Met vriendelijke groet,

Benno Goedhart

**Comment by bgoedhart** [comment]
Ok dan doe ik nog even een test betaling en wacht af of Mollie terug komt met een foutmelding.

**Comment by Wouter0100** [comment]
Howdy! Zouden jullie even error logging aan willen zetten en kijken wat er in de errors komt, als Mollie de callback.php probeert aan te roepen?

Kunnen jullie doen door even op een paar plekken in de callback.php de volgende regels te plaatsen:
```
ini_set("error_reporting", E_ALL & ~E_NOTICE & ~E_DEPRECATED);
ini_set("log_errors", 1);
```

Ik vraag jullie expres om dit op een paar plekken te doen, omdat WHMCS dit blijkbaar overschrijft. Grr. Bij voorkeur dus even onder regel 6 en nogmaals bij regel 12.

**Comment by thehosting4you** [comment]
Als dit de goede url: http://klanten.thehosting4you.nl/modules/gateways/mollie/callback.php is krijg ik deze melding: De pagina op klanten.thehosting4you.nl werkt niet
klanten.thehosting4you.nl kan dit verzoek momenteel niet verwerken.
HTTP ERROR 500

Met vriendelijk groet André

**Comment by Wouter0100** [comment]
De URL moet je ook niet handmatig aanroepen, maar via een testbetaling. Handmatig aanroepen geeft hij inderdaad een 500 terug. Zie https://github.com/0100Dev/WHMCS-Mollie/blob/cb6ec43159b1e59c0c277cf378cb6d3de45232ab/src/mollie/callback.php#L21-L39.

**Comment by thehosting4you** [comment]
> De URL moet je ook niet handmatig aanroepen, maar via een testbetaling. Handmatig aanroepen geeft hij inderdaad een 500 terug. Zie https://github.com/0100Dev/WHMCS-Mollie/blob/cb6ec43159b1e59c0c277cf378cb6d3de45232ab/src/mollie/callback.php#L21-L39.

Er zijn vandaag klanten bij mij geweest die betaling hebben gedaan zonder problemen.
de facturen worden netjes op betaald gezet en teven op de factuur de transactie id.

Ik hoop dat dit voldoende is.

**Comment by Wouter0100** [comment]
Dan was het probleem dus niet aan onze kant. Is het bij starter ook opgelost, @bgoedhart ?

**Comment by miroderuiter** [comment]
Ik ben een collega van Benno Goedhart. We hebben in het bestand callback.php de regels header('HTTP/1.1 500 etc.) uitgecommentarieerd. Nu lijkt de betaling wel goed te gaan. We krijgen van Mollie ook geen foutmeldingen terug.

**Comment by Wouter0100** [comment]
@miroderuiter Heb je ook de `exit();` eruit gehaald? Deze is namelijk echt required, en als dat header weghalen effect had, was er iets fout met de callback vanuit Mollie (of de betaling was al verwerkt, of hij bestond niet). 

Gaf Mollie die foutmelding terug, of hadden jullie het zelf getest wat die error gaf?

**Comment by miroderuiter** [comment]
Nee, de exit(); heb ik laten staan. Mollie gaf geen foutmelding terug. We wilden eigenlijk door het verwijderen van de header() regel kijken of er een foutmelding in beeld kwam, maar heel verassend ging het ineens goed.

**Comment by Wouter0100** [comment]
Hmm, vreemd. Dan komt het aanroepen van de callback in een bepaald scenario terecht waar hij niet in zou moeten komen. Daarom sturen we dus ook een error, wat Mollie mooi oppakt.
