### ISSUE TITLE
Conflict met WHMCS source mollieideal

### ISSUE THREAD

**Issue by Wouter0100** [0100Dev/WHMCS-Mollie#15]
Kijken wat de mogelijkheden zijn. Veel mensen hebben de gateway al in gebruik, dus naam veranderen kan niet zomaar. Eventueel naast elkaar nog laten draaien, of goed documenteren. BC breaking.

**Comment by ExchequerNL** [comment]
Blijft toch problematisch dit. Met de automatische updates in WHMCS is het erger geworden. Elke automatische update is ideal weer stuk. Laatste keer vergeten en meteen allerlei transacties die hele andere klantnamen kregen en natuurlijk meldingen van fouten door klanten. Jullie ideal bestand even hernoemen naar iets als ideal0100dev.php lijkt mij een oplossing waar niemand echt een probleem mee kan hebben.

**Comment by Wouter0100** [comment]
Hmmm, simpel renamen kan niet, doordat bedrijven er al gebruik van maken. Dan zouden we beide naast elkaar moeten laten "leven", maar ook dat liever niet, want dan komt hij 2 keer in het WHMCS Gateway overzicht te staan.

**Comment by thehosting4you** [comment]
Ik denk dat het wel mogelijk is. Want ik heb heb nu ook de zelfde problemen. Dus ik denk dat die bedrijven dat ook hebben. En het aanpassen is snel gedaan je moet dan alleen een geforceerde update doen.

**Comment by rvhelden** [comment]
Ik zit met hetzelfde probleem, je zou er natuurlijk heel groot bij kunnen zetten dat er een breaking change in deze update zit

**Comment by Wouter0100** [comment]
Dat zal dan wel de enige oplossing zijn. Als iemand nog met een ander idee komt. Hij is sowieso open voor PR's. Anders probeer ik er deze week, misschien volgende week, naar te kijken.

**Comment by ExchequerNL** [comment]
@Wouter0100 
Ik snap oprecht de logica achter het bezwaar niet. Als in een nieuwe update alle files naar het nieuwe bestand verwijzen is voor allle users die updaten het probleem opgelost. Users die om wat voor reden dan ook perse het oude bestand willen gebruiken (omdat ze oudere versie gebruiken?) hoeven niet perse te updaten en voor hun verandert er dus niet.

Overigens is de enige reden om dat niet te willen die ik kan bedenken dat je mogelijk na de namechange even de ideal gateway opnieuw moet activeren en de api key copy pasten, maar dat merk je snel genoeg. Dat is voor mij zeker geen reden om dit conflict te laten bestaan. Of zie ik hier een complexiteit over het hoofd? 

 Updaten van WHMCS is nu erg tricky. Ik heb al een paar betalingen gehad die door de war gingen (toegeschreven aan foute user binnen mollie panel) dus dat wordt administratief een feest :P.  Dus heel 
heel fijn als je er naar gaat kijken! Denk dat ik binnenkort ook eens aan jullie recurring plugin begin (mits 7.4 compatible).

**Comment by Wouter0100** [comment]
Fix staat live in V1.1.

**Comment by camielpeeters** [comment]
Ik heb een clean install van whmcs, en de basis whmcs gateway die whmcs er in heeft zitten werkt dus niet. Nu ben ik er niet helemaal uit wat hier nu de oplossing voor is, renamen van deze mollie gateway? any tips?

**Comment by thehosting4you** [comment]
Welke versie van whmcs en van deze module.

**Comment by camielpeeters** [comment]
ik heb deze plugin/gateway voor mollie nog niet in gebruik, gister de laatste versie hiervan gedownload. Ik heb de meest recentere versie van whmcs, en daar wordt niet gereageerd op mijn mollie partner id en krijg ik error's over betaalgegevens die niet correct zijn etc.
Ik zou dus graag weten hoe ik deze mollie brug er in gooi en kan laten werken, er zijn nog geen betalingen gedaan in de whmcs met mollie dus ik kan nog alle kanten op dacht ik zo.

**Comment by thehosting4you** [comment]
De plugin van whmcs links laten liggen, is niet up to date.
Deze kunt u installeren volgens doc en dan activeren binnen whmcs gegevens invullen en dan kunt u hem gebruiken.

**Comment by camielpeeters** [comment]
Ik heb jullie prachtige whmcs plugin voor mollie standaard gateway’s geïnstalleerd en alles loopt soepel, helaas zie ik alleen vlak voor het moment van een testbetaling op mijn afschrift, de naam van ontvanger “bedrijfsnaam via Mollie” staan. Enig idee of dit via jullie plugin valt aan te passen? Ik heb liever zo min mogelijk mollie-reclame maar weet niet of dit aan te passen valt.

Met vriendelijke groet, 
Camiel

**Comment by camielpeeters** [comment]
Ik kwam bij toeval deze mail tegen welke de vraag op mijn situatie al beantwoord, het komt door mollie en zal dus on- aanpasbaar zijn.
Ik ben dit jaar eindelijk klaar voor het configureren van incasso via jullie betaalde plugin, mijn vraag rest nog:
Moet ik na aanschaf van jullie plugin bij mollie iets als een incasso-machtig aanvragen daar en/of bij mijn bank? Ik weet dat mollie ook ecurring aanbied wat ik erg duur vind en hoop te voorkomen via jullie plugin.

Hoor graag tips! 

Met vriendelijke groet, 
Camiel Peeters
