### ISSUE TITLE
Factuur nummer 

### ISSUE THREAD

**Issue by thehosting4you** [0100Dev/WHMCS-Mollie#16]
Hallo,

Sinds whmcs heeft geupdate naar Versie: 7.0.1 wordt de factuur nummer niet meer mee gestuurd.

Kan dit spoedig worden opgelost.

Met vriendelijk groet André

**Comment by Wouter0100** [comment]
Wat is precies het probleem? "Factuur nummer niet meer mee gestuurd" is redelijk breed.

Helaas kan ik al wel zeggen dat, zolang niemand er tijd voor heeft, het niet op korte termijn opgelost gaat worden. Het betreft een open source project dat wij (en andere) in vrije tijd/vrije wil uitvoeren.

**Comment by thehosting4you** [comment]
Beste,

Zoals u ziet zit er geen factuur in de omschrijving waardoor het voor de klanten niet kunnen controleren of de factuur nummer goed is
![mollie-geen-factuur](https://cloud.githubusercontent.com/assets/8598623/19688870/ae646534-9acb-11e6-8b16-d670e1844240.png)

Hier de instelling binnen whmcs:

![mollie-whmcs-factuur](https://cloud.githubusercontent.com/assets/8598623/19688936/f3d3ef4a-9acb-11e6-9bf8-40cbfa44c75a.png)

Heeft u hier genoeg info aan.

Met vriendelijke groet André

**Comment by Wouter0100** [comment]
Top, bedankt voor de toevoeging aan het issue.

**Comment by thehosting4you** [comment]
Hallo @Wouter0100 ,

Ik heb even gekeken en kom tot de ontdekking dat in de gateway_mollie geen gegevens worden geplaats na de update van whmcs.
Is er iets wat ik kan veranderen zodat het weer gaat werken?

Met vriendelijk groet André

**Comment by Wouter0100** [comment]
Probeer de gateway is opnieuw te installeren, vermoedelijk heeft dit te maken met #15.

**Comment by thehosting4you** [comment]
Hallo @Wouter0100,

Ik ben aan het testen geweest en heeft inderdaad te maken met dat probleem want ik de whmcs installatie map zit de zelfde bestand(mollieideal.php) die jij ook gebruikt.

Naar deze verwijderd te hebben en jou module op nieuwe geinstalleerd is het probleem verholpen.

Met vriendelijk groet André
