### ISSUE TITLE
WHMCS 7

### ISSUE THREAD

**Issue by digiexpert** [0100Dev/WHMCS-Mollie#17]
iDeal werkt niet meer. Wanneer er betaling gedaan moet worden, dan krijg je de melding:

De betaling kon niet aangemaakt worden.

Foutmelding: A fetch was issued without specification of 'partnerid'.

**Comment by thehosting4you** [comment]
Hij werkt bij mij prima< weet u zeker dat het id goed is?

**Comment by Wouter0100** [comment]
Zie #17 en #15.
