### ISSUE TITLE
KBC betalingen

### ISSUE THREAD

**Issue by Jaspaert** [0100Dev/WHMCS-Mollie#18]
Beste 

Ik lees dat alle betaalmogelijkheden hier zijn inbegrepen, echter zie ik de KBC/CBC optie nog niet.

Zal deze in de toekomst nog toegevoegd worden?

Met vriendelijke groeten
Kurt

**Comment by Wouter0100** [comment]
Hmm, is deze wellicht nieuw? Is er nog niet, lijkt het inderdaad op.

**Comment by thehosting4you** [comment]
Hallo ,

In de module als afbeelding staat er wel tussen :-) 
[http://klanten.thehosting4you.nl/modules/gateways/mollie/vendor/Mollie/examples/6-list-activated-methods.php](url)

M.v.g.

**Comment by Wouter0100** [comment]
@thehosting4you helaas wil dat niet zeggen dat deze module hem dan ook direct ondersteunt. Andere modules zouden dat eventueel wel kunnen, maar op de manier hoe WHMCS en deze module opgebouwd is kan dat hierbij niet automatisch.

**Comment by LoccoPalace** [comment]
Enige update voor KBC en ING, heb KBC al een jaar op mijn webshops draaien en ING is er nu bijgekomen helaas nog niet hier.

**Comment by Wouter0100** [comment]
Wat bedoel je, @LoccoPalace? Helaas is deze nog niet ingepland. Ik zet hem even op help wanted, want mensen zijn vrij een PR aan te maken.

Wanneer iemand deze integratie wenst, kunnen we dit ook tegen commerciële support inbouwen. Meer informatie [hier](https://0100dev.nl/modules/whmcs#WHMCS Mollie).

**Comment by LoccoPalace** [comment]
Raar dat deze zo lang duurt bij Mollie dan, want heb zelf nu Belfius, KBC, ING en alle andere via Mollie bekomen voor mijn webshops en toch al meer dan een jaar nu, buiten ING, want die is recent bijgekomen.
Daarom mijn vraag hier ook. Niet dringend voor mij aangezien ik meeste werk met betaal links via plink.

**Comment by MaikelVEGroup** [comment]
KBC Werdt het meeste gebruikt en n uben ik verplicht om versie 1.1 te gebruiken waar KBC wel te verkrijgen is...

**Comment by MaikelVEGroup** [comment]
Indien KBC, ING, EPS en Giropay toegevoegd wil ik overschakelen naar jullie addon, nu gebruikt ik een iets wat outdated van iemand anders

**Comment by Wouter0100** [comment]
@MaikelVEGroup toevallig heb ik in de planning staan hier vanavond aan te werken. We hebben een business support verzoek binnen gekregen die deze PR vergoed.

**Comment by Wouter0100** [comment]
Zit in laatste release.
