### ISSUE TITLE
Mollie SEPA-betalingen in WHMCS

### ISSUE THREAD

**Issue by twelvetrains** [0100Dev/WHMCS-Mollie#19]
Hallo,

Ik heb begrepen dat Mollie Direct Debit (SEPA-incasso) nu mogelijk is in de WHMCS plugin. Ik heb de optie ook geselecteerd in WHMCS, zie schermafbeelding.

Maar bij het testen van een Mollie Direct Debit betaling geeft de browser een 'HTTP ERROR 500' foutmelding. Graag hoor ik waaraan die zou kunnen liggen. De API is uiteraard ook ingesteld en de overige betalingsmogelijkheden zoals iDeal werken zonder probleem.

Ik hoor het heel graag.

Alvast dank,
Carsten

<img width="977" alt="schermafbeelding 2016-12-02 om 15 27 04" src="https://cloud.githubusercontent.com/assets/13319952/20837347/fce54052-b8a3-11e6-8d6c-0f6735985ebd.png">

**Comment by Wouter0100** [comment]
Welke error krijg je precies? Zonder die informatie kunnen we helaas niet verder helpen. Zet even Display Errors in Setup => General Settings => Other => Display Errors aan.

**Comment by twelvetrains** [comment]
Dank je wel voor je snelle antwoord! Dit zijn de php foutmeldingen:

--

Fatal error: Uncaught exception 'Mollie_API_Exception' with message 'Error executing API call (request): The payment method is not activated on your account.' in /home/twelve1q/public_html/accounts/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Resource/Base.php:238 Stack trace: #0 /home/twelve1q/public_html/accounts/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Resource/Base.php(76): Mollie_API_Resource_Base->performApiCall('POST', 'payments', '{"amount":"1.00...') #1 /home/twelve1q/public_html/accounts/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Resource/Base.php(185): Mollie_API_Resource_Base->rest_create('payments', '{"amount":"1.00...') #2 /home/twelve1q/public_html/accounts/modules/gateways/mollie/mollie.php(96): Mollie_API_Resource_Base->create(Array) #3 /home/twelve1q/public_html/accounts/modules/gateways/molliedirectdebit.php(19): mollie_link(Array, 'directdebit') #4 /home/twelve1q/public_html/accounts/includes/classes/WHMCS/Module/AbstractModule.php(0): molliedirectdebit_link(Array) #5 /hom in /home/twelve1q/public_html/accounts/includes/classes/WHMCS/Terminus.php on line 0

--

In de eerste regels staat 'The payment method is not activated on your account.'  SEPA is geactiveerd in Mollie.nl, zie schermafbeelding. Verder hoop ik dat je wijzier wordt van de foutmeldingen. Dank je!

<img width="825" alt="schermafbeelding 2016-12-02 om 16 15 48" src="https://cloud.githubusercontent.com/assets/13319952/20838933/ef253826-b8aa-11e6-8405-da0dc1fae85b.png">

**Comment by Wouter0100** [comment]
Staat hij ook geactiveerd voor je websiteprofiel?

**Comment by twelvetrains** [comment]
Ja, daar staat die ook geactiveerd, zie schermafbeelding. Wellicht is er nog een plek waar die geactiveerd moet zijn?

![](https://cloud.githubusercontent.com/assets/13319952/20838933/ef253826-b8aa-11e6-8405-da0dc1fae85b.png)

**Comment by Wouter0100** [comment]
Ook zeker dat je dat profiel gebruikt? Ik zou anders even Mollie contacteren. Er is duidelijk iets fout met je profiel.

**Comment by twelvetrains** [comment]
Binnen het Mollie heb ik maar één website profiel. Ik zal Mollie contacteren hierover. Dank je tot dusver!

**Comment by twelvetrains** [comment]
Net met Mollie gesproken. Zij bleven het hebben over éénmalige incasso en recurring incasso en volgens hen klinkt het alsof het misgaat omdat de plugin niet is ingesteld op recurring incassos. En hij noemde steeds de 'first payment' in verband met recurrent incassos. Ik ga er vanuit dat de 'Mollie Direct Debit' optie juist die first payment regelt, toch?

**Comment by Wouter0100** [comment]
Dat is onderdeel van Mollie Recurring, daar zijn we een aparte plugin voor aan het maken. Automatisch Incasso zou hier los van moeten staan.

**Comment by twelvetrains** [comment]
Aha, daarom begrijp ik er steeds minder van geloof ik. 'Automatisch incasso' is dus _niet_ hetzelfde als 'Mollie Recurring'? En wat is dan 'Mollie Direct Debit'? Ik ga ervan uit dat het dit is: https://www.mollie.com/nl/directdebit

Daar staat dat het gebruikt kan worden voor "het afrekenen van maandelijkse betalingen voor abonnementen of donaties." Dat is in mijn wereld automatische incasso's.

En nu kom ik terug naar mijn WHMCS waar 'Mollie Directs Debit' aanstaat (wat dus niet werkt) en mijn vraag is: Wat kan ik 'Mollie Directs Debit' dan precies voor gebruiken als het niet voor automatische incassos/recurrings zijn?

**Comment by Wouter0100** [comment]
Ik zit ook even te kijken inderdaad, moet zeggen dat ik niet erg verdiept heb hierin. Gebruik 't zelf niet, koppel je z.s.m. terug.

**Comment by twelvetrains** [comment]
Okay, dank je wel voor de moeite.

**Comment by Wouter0100** [comment]
Dit is echt een probleem met je account. Hier werkt alles naar behoren. Ze hebben 2 diensten:
Direct Debit/Automatisch Incasso
Mollie Recurring

Mollie Recurring is een verbeterde all-in oplossing. Bij Automatisch Incasso moeten ze handmatig de incasso initialiseren. We zullen op korte termijn voor Mollie Recurring een plugin voor WHMCS verkopen, die we recentelijk ontwikkeld hebben.

**Comment by twelvetrains** [comment]
Inmiddels weer met Mollie gesproken en gemaild. Joris van der Hoeven (Mollie) schrijft het volgende:

"Ik heb je account bekeken en zit dat incasso gewoon actief staat voor je account, alle vinkjes staan correct. Wellicht dat er toch iets niet goed gaat in de module."

Ik weet dat dit een gratis module is maar is er niet ergens een precieze uitleg over hoe het een en ander in WHMCH ingesteld moet worden? Werkt het alleen met bepaalde soort producten? 

Als Direct Debit/Automatisch Incasso bij jullie gewoon werkt, dan is er toch iets wat niet goed is, of in de module of in WHMCS of een combinatie.

**Comment by Wouter0100** [comment]
Gebruik je wel de juiste token? Er is niet zo heel veel configuratie, en de error is best specifiek aan Mollie. Code verschilt ook niet tussen iDeal/Paysafecard (of enig andere betaalmethode) en Direct Debit. 

Verdere instellingen in WHMCS zijn niet van toepassing op deze module, zolang de API keys maar juist ingesteld staan in het Payment Gateways overzicht.

**Comment by twelvetrains** [comment]
Dank je voor je snelle reactie. Ik heb zo'n idee dat ik iets over het hoofd zie, daarom vroeg ik naar verdere instellingen. De juist API code is ingevuld, namelijk dezelfde als wat bij de andere betalingsmethodes is ingevuld. En de andere methodes werken gewoon zonder probleem.

Het is dus iets specifieks met de Direct Debit/Automatisch Incasso. Ik begrijp daarom ook goed dat het op een instellingsfout bij Mollie lijkt.

**Comment by Wouter0100** [comment]
Ben evt. wel bereid deze keer te kijken, als je me even een mailtje stuurt op wvanos@0100dev.nl, kunnen we het even verder uitzoeken. De conclusie van dat onderzoek zal ik dat vermeldden in dit issue.

**Comment by SjamonDaal** [comment]
Hi, 
Ik wil even mededelen dat ik tegen het zelfde probleem aanloop bij deze module bij Automatisch incasso.
Ik heb echter geen idee waar het probleem precies zit maar zoals @twelvetrains meld blijkt het probleem niet bij mollie te zitten.

Ik kijk uit naar een eventuele oplossing.

**Comment by Wouter0100** [comment]
Helaas heeft @twelvetrains nog geen e-mail gestuurd. Is het mogelijk dat jij dit doet, @SjamonDaal? Dan zullen we kijken naar een oplossing.

**Comment by SjamonDaal** [comment]
Hi Wouter,

Je had me een bericht gestuurd of ik je een mail wou sturen.
Dat is geen probleem maar je mail staat op het moment niet meer in de posts.

**Comment by SjamonDaal** [comment]
Hi Wouter,

Zoals gevraagd heb ik een email gestuurd.
Ik wacht op een reactie zodat we dit probleem gezamenlijk kunnen bekijken.

**Comment by Wouter0100** [comment]
Yes, thanks. Lijkt echt op een probleem bij Mollie.

**Comment by twelvetrains** [comment]
Dit kreeg ik te horen van Nick bij Mollie:

--

SEPA-incasso is niet meer beschikbaar in het betaalscherm, maar enkel nog via ons Recurring product te gebruiken. De API van Recurring zou dan geïntegreerd moeten worden: https://www.mollie.com/nl/docs/recurring.

--

De SEPA-incasso kan dus uit de module.

**Comment by Wouter0100** [comment]
Vreemd. Ze geven het nog wel aan bij "Mollie API" onder aan bij op [deze](https://www.mollie.com/nl/directdebit) pagina.

**Comment by Wouter0100** [comment]
Reopend om Direct Debit eruit te halen.

**Comment by SjamonDaal** [comment]
Als je Direct Debit eruit haalt, stop je dan Recurring er ook in? 😅

**Comment by Wouter0100** [comment]
Nee, dit is een apart, betaald, product omdat het veel meer onderhoud en support vereist. Mollie Recurring is ook een extra dienst van Mollie.

**Comment by SjamonDaal** [comment]
Oké, heb je dit product wel? Zo ja, waar kan ik hem dan vinden?

**Comment by Wouter0100** [comment]
`We releasen binnenkort een intergratie voor Mollie Recurring in WHMCS.`

Komt er dus nog aan, ik verwacht ergens volgende week. Dan is hij volledig getest en zal uit beta-fase gaan.

**Comment by Wouter0100** [comment]
@SjamonDaal @twelvetrains @torriva

Mollie Recurring gateway is nu [hier](https://0100dev.nl/cart.php?a=add&pid=70) te verkrijgen. Hij staat nog niet op onze website, maar hier zal aan gewerkt worden. Informatie zullen we ook nog uitbreiden, maar bij vragen kan er altijd een ticket aangemaakt worden of een e-mail gestuurd worden op support@0100dev.nl. Omdat dit een betaald product is geven we hier gewoon inhoudelijke support over, inclusief fixes e.d..

**Comment by Wouter0100** [comment]
Verwijderd uit V1.1 door 034fc6e.

**Comment by Wouter0100** [comment]
Voor de mensen die hier via Google komen. De WHMCS Mollie Recurring gateway is vanaf nu via onze website verkrijgbaar. Zie https://0100dev.nl/whmcsmodules
