### ISSUE TITLE
Email template betaal url werkt niet

### ISSUE THREAD

**Issue by ExchequerNL** [0100Dev/WHMCS-Mollie#20]
In de factuurmail wordt een element geplaats:

> U kunt uw factuur direct voldoen via deze link: 
> 
> Select bank: Pay with iDeal

Echter het klikken op de url lijkt er niet voor te zorgen dat de gebruiker direct naar de ideal gateway van mollie wordt verwezen. Als ik een mail terug kijk via client>email dan vernieuwd hij simpelweg de pagina. Is het inloggen verplicht of kan de klant ook daadwerkelijk direct betalen vanuit de mail?

ps
De versie die ik gebruik stamt uit 19 mei 2016 (bij releases zie ik alleen de 1.0).

**Comment by Wouter0100** [comment]
Betalingen werken alleen via de website, niet via een e-mail. Klanten moeten hiervoor ingelogd zijn, maar dit is zoals WHMCS werkt. Hier lijkt me niet iets specifieks aan in deze gateway.
