### ISSUE TITLE
Probleem bij callback webhookUrl in WHMCS 7.1

### ISSUE THREAD

**Issue by ms0ft** [0100Dev/WHMCS-Mollie#21]
Beste Wouter,

We hebben recent een WHMCS update gedaan van 6.3 naar 7.1 en hierbij ook je module geupdate naar de laatste versie.
Na deze updates werkt de webhookUrl niet meer. Door een dubbele / in het pad wordt twee keer een 301 redirect gegenereerd. Hierbij vallen de POST variabelen van Mollie weg en komt er een server 500 melding.
> "POST //modules/gateways/mollie/callback.php HTTP/1.0" 301
> "POST /modules/gateways/mollie/callback.php HTTP/1.0" 301 
> "POST /modules/gateways/mollie/callback.php HTTP/1.0" 500 

Als fix heb ik in mollie.php op regel 91 een aanpassing gedaan:
`                'webhookUrl' => $params['systemurl'] . '/modules/gateways/mollie/callback.php',`
naar
`                'webhookUrl' => $params['systemurl'] . 'modules/gateways/mollie/callback.php',`

Dit werkt voor ons, maar voor een algemene fix zal hier denk ik wat meer intelligentie in moeten die een check doet of de slash nodig is of niet.

Alvast bedankt,
Michael

**Comment by Wouter0100** [comment]
Dank voor het issue. Ik zie inderdaad dat dit voor potentiële problemen kan zorgen. Zou je hier wellicht een PR voor willen openen? Dit zou iedereen die gebruikt maakt van deze gateway veel helpen.

**Comment by qarizma** [comment]
Ik heb een PR aangemaakt die dit probleem moet oplossen.
