### ISSUE TITLE
Fout bij het openen van de betaalmethodes.

### ISSUE THREAD

**Issue by thehosting4you** [0100Dev/WHMCS-Mollie#22]
Hallo,

Bij het openen in whmcs en dan instellingen en betaal methodes krijg ik deze foutmelding: Fatal error: Cannot redeclare mollieideal_config() in on line 0

Wie kan mij hier mee helpen.

Met vriendelijk groet André

**Comment by Wouter0100** [comment]
Probeer is opnieuw te deployen, zou het moeten oplossen, omdat WHMCS standaard `mollieideal.php` meegeeft.

**Comment by thehosting4you** [comment]
Beste,


Moet je die van whmcs gebruiken of die in de scr staat.

M.v.g.

**Comment by Wouter0100** [comment]
Die van ons. Niet die van WHMCS.

**Comment by thehosting4you** [comment]
Hallo @Wouter0100  ,

Ik heb de script opnieuwe gedownloaden en geinstalleerd de whmcs molieideal.php verwijderd en die in het bestand zit geplaats maar ik heb nog steeds de zelfde fout :-) 

Ik hoop dat jij mij kunt helpen.

**Comment by Wouter0100** [comment]
mollieideal.php niet verwijderen, maar overschrijven met die van ons.

**Comment by thehosting4you** [comment]
Hallo

Even die jou weg gehaald en die van whmcs er in gezet maar nog de zelfde fout.
Ik heb even een ticket aangemaakt voor whmcs ik kom erop terug.

M.v.g.

**Comment by thehosting4you** [comment]
Hallo @Wouter0100 

Dit heb ik als antwoord?

> As suspected, this was an issue with third party payment gateway modules you have added to modules/gateways/ that are also using the same class/functions as the built in WHMCS mollieideal.php file.

>I moved this file to mollieideal.php.PWM-658875.chance.04.19.2017.bak and this resolved the issue.

>However, since the third party gateway modules are at fault here, you will need to contact the developer of these modules to have them resolve this.

Hoe kun jij dit oplossen, want naar elke update is dit een probleem?

Met vriendelijk groet André

**Comment by Wouter0100** [comment]
Dit is dan een duplicate van #15. Issue staat hier al voor open.

**Comment by thehosting4you** [comment]
Ik heb dit nu kunnen oplossen door de mollieideal-whmcs.php te hernoemen.

Ik hoop wel dat dit zo snel mogelijk wordt opgelost.

M.v.g.
