### ISSUE TITLE
Geen betaalbevestiging WHMCS 7.2

### ISSUE THREAD

**Issue by ExchequerNL** [0100Dev/WHMCS-Mollie#25]
Ik ben bezig met WHMCS 7.2 op een testomgeving en ben hiervoor alle gateways e.d. opnieuw aan het installeren. Bij deze plugin loop ik tegen het probleem aan dat betalingen niet worden bevestigd.

Het selecteren van de gateway gaat goed, daarna wordt er ook goed doorverwezen naar de mollie test betaalpagina (bijvoorbeeld iDeal of Bitcon). Na het kiezen van de door te geven status wordt er netjes terug verwezen naar de WHMCS factuur. Daar staat echter vervolgens " Checking your payment.. Please wait."  De factuur blijft eeuwig op unpaid staan. CSF firewall volledig uitschakelen verhelpt het probleem niet.

De module logs bleven helaas leeg. Wel valt op dat de url deze is: https://domein.nl//viewinvoice.php?id=452&check_payment=179 . Er zit een dubbele slash in voor viewinvoice (maar de url an sich werkt wel). 

Iemand een idee hoe ik dit aan de praat krijg?

Update: Met WHMCS 7.1.2 loop ik helaas tegen hetzelfde probleem aan. De status " betaald"  wordt niet doorgegeven aan WHMCS. Als ik bij Mollie kijk dan blijkt de webhook status 500 te krijgen:

Webhook failed (Received HTTP code 500 from proxy after CONNECT)

Als ik in callback.php kijk dan zijn er echter minstens 4 mogelijkheden die status 500 opleveren (not found, not open, arg mismatch). Clean install precies hetzelfde probleem. Transaction log maakt geen melding (wel als ik callback.php handmatig  bezoek, dan komt de arg mismatch in de logs.

**Comment by ExchequerNL** [comment]
Het probleem is opgelost. Het bleek dat ik een fout had gemaakt in het CNAME record waardoor de callaback url niet aankwam. Zelf niet gemerkt omdat ik lokaal een andere hosts bestand gebruik.

**Comment by Wouter0100** [comment]
Top!
