### ISSUE TITLE
Bitcoin betalingen werken niet

### ISSUE THREAD

**Issue by qarizma** [0100Dev/WHMCS-Mollie#26]
Bitcoin betalingen werken in deze plugin niet. Na bitcoin betalingen blijft de invoice als onbetaald gemarkeerd.

Contact met Mollie gehad, die beweren het volgende:

> Deze transactie is mislukt omdat de link verlopen is.
Het bedrag kwam pas binnen nadat de link is verlopen.

**Comment by Wouter0100** [comment]
Hmm, Mollie beweert dat de transactie dus simpelweg te laat binnenkwam. Is dit dan een fout in de module, of had de klant dan eerder moeten betalen? Volgensmij geven wij nergens een verlooptijd mee, Mollie beheert dit zelf. Bitcoin links verlopen namelijk na [15 minuten](https://www.mollie.com/nl/docs/status#when-does-a-payment-expire).

**Comment by qarizma** [comment]
De klant heeft bij alle momenten de betaling direct gedaan. De module markeert het niet als betaald, terwijl Mollie het geld wel binnen heeft.

**Comment by Wouter0100** [comment]
Vreemd dat Mollie dan zegt dat de link verlopen is. Heb je toevallig een screenshot van de "geschiedenis" van de betaling (uit het Mollie dashboard)? Zoals deze (maar dan voor de mislukte Bitcoin betaling):
![image](https://user-images.githubusercontent.com/864520/29967917-57170e60-8f19-11e7-9a07-0c816379a7a2.png)

Hopelijk kan ik van deze gegevens beoordelen waar het fout gaat.

**Comment by qarizma** [comment]
Ja dat heb ik:
![40e0909f128fa7b189adc3269308a570](https://user-images.githubusercontent.com/8611981/29968174-b5ffdcda-8f1a-11e7-81fb-74be1ac3bbfc.png)

Ik kan hier ook niet uithalen wat er nou precies gebeurt is. Heeft WHMCS nog relevante logs hiervoor?

**Comment by Wouter0100** [comment]
Helaas zie ik in die screenshot niet dat Mollie aangeeft dat ze het geld binnen hebben? Normaliter moet hij dan aangeven dat de Bitcoin betaling betaald is, zoals bij mij te zien. WHMCS is hierin niet relevant, omdat het bij Mollie dus al fout gaat (betaling word niet verwerkt). De reden van de mislukte betaling lijkt de timeout van 15 minuten te zijn.

Die "Webhook succesvol aangeroepen" geeft terug aan WHMCS dat de betaling gefaald is, zodat wij de betaling kunnen sluiten. 

Helaas lijkt het er niet op dat wij een andere timeout of het aantal goedkeuringen kunnen opgeven, dus ik ben bang dat het echt een issue van Mollie is.

**Comment by qarizma** [comment]
Je hebt gelijk, ik heb weer contact opgenomen met Mollie, eens kijken wat die hier over zeggen.

**Comment by Wouter0100** [comment]
Top, dan sluit ik hierbij het issue. Als uiteindelijk blijkt dat we iets kunnen aanpassen in de gateway om bijv. die timeout te verlengen, hoor ik dat wel. Maar, het lijkt me eerlijk gezegd een groter issue van Mollie met bitcoins betalingen..
