### ISSUE TITLE
WHMCS 7.3.0 overwrites mollieideal.php

### ISSUE THREAD

**Issue by qarizma** [0100Dev/WHMCS-Mollie#28]
De nieuwe WHMCS update komt met een officiële Mollie gateway genaamd mollieideal.php. Dit is de exacte naam zoals deze externe module. Dus na het updaten vervang je automatisch het bestand door een compleet ander bestand waardoor iDeal niet meer werkt. Na een hele middag zoeken ben ik er uiteindelijk achter gekomen.

De officiele module werkt overigens niet. Conclusie: na updaten deze module opnieuw uploaden.

Graag de naam mollieideal.php veranderen naar iets unieks, dan lijkt het mij opgelost.

Thanks

**Comment by Wouter0100** [comment]
Dit issue is al open, zie #15. Het vervelende is, als we het renamen moeten we dit duidelijk vermelden, of beide laten bestaan naast elkaar.
