### ISSUE TITLE
Installatie wordt niet uitgevoerd.

### ISSUE THREAD

**Issue by Staalkoper** [0100Dev/WHMCS-Mollie#3]
Nadat ik connectie heb gemaakt met SSH en in de root van de WHMCS folder zit voer ik de commando 
`git clone --recursive https://github.com/0100Dev/WHMCS-Mollie.git /tmp/whmcs && sudo mv /tmp/whmcs/src ./modules/gateways/` 
uit alleen krijg ik 
`-bash: git: command not found` 
als reactie.

Hoe kan dit opgelost worden?

**Comment by Wouter0100** [comment]
Door GIT te installeren op je server. Welk OS draait er op je server?

Probeer anders een van deze twee commando's:
`sudo yum install git`
`sudo apt-get install git`

**Comment by Staalkoper** [comment]
Bedankt! Stukje verder :)

Uiteraard kan ik nu wel ´ git clone --recursive https://github.com/0100Dev/WHMCS-Mollie.git /tmp/whmcs && sudo mv /tmp/whmcs/src ./modules/gateways/ ´ uitvoeren alleen krijg ik de volgende onderstaande reactie:

´root@gamma [/home/XXXX/public_html/XXX]#  git clone --recursive https://github.com/0100Dev/WHMCS-Mollie.                                                          git /tmp/whmcs && sudo mv /tmp/whmcs/src ./modules/gateways/
Initialized empty Git repository in /tmp/whmcs/.git/
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 98
Receiving objects: 100% (101/101), 162.85 KiB, done.
Resolving deltas: 100% (46/46), done.
Submodule 'src/mollie/vendor/Mollie' (https://github.com/mollie/mollie-api-php.git) registered for path 'src /mollie/vendor/Mollie'
Initialized empty Git repository in /tmp/whmcs/src/mollie/vendor/Mollie/.git/
remote: Counting objects: 836, done.
remote: Total 836 (delta 0), reused 0 (delta 0), pack-reused 836
Receiving objects: 100% (836/836), 651.98 KiB | 867 KiB/s, done.
Resolving deltas: 100% (407/407), done.
Submodule path 'src/mollie/vendor/Mollie': checked out 804aa2e3a80f27c0208557f258504d147bdd4b07'
´

En daarmee eindigt het. Het lijkt erop dat de installatie nog niet helemaal voltooid is omdat de payment gateway de modules nog niet toont.

**Comment by Wouter0100** [comment]
`mv` geeft geen output. Staat er vervolgens niks in de `/modules/gateways` folder? Anders moet je even alles handmatig verplaatsen uit de `/tmp/whmcs/src` folder naar de `/modules/gateways` folder.

**Comment by Staalkoper** [comment]
Bedankt voor je snelle reacties @Wouter0100 

`/tmp/whmcs/src` bestaat niet. 
`/tmp/whmcs/` bestaat wel.

**Comment by Wouter0100** [comment]
Dan is het al ergens naar toe verplaatst. Zat je tijdens het uitvoeren van het commando wel in WHMCS's root folder?

**Comment by Staalkoper** [comment]
Ja zeker

Als ik weer in bereik ben van de server zal ik zoeken naar de folders.

Op za 14 nov. 2015 20:45 schreef Wouter van Os <notifications@github.com>:

**Comment by Wouter0100** [comment]
Top, fijn te horen dat het hierbij ogpelost is! Die `mv`-error heeft volgensmij te maken dat ze niet op dezelfde device staan.. Ik vervang `mv` in het voorbeeld commando daarom nu even met `cp`. Thx.
