### ISSUE TITLE
iDeal callback not working after update

### ISSUE THREAD

**Issue by thehosting4you** [0100Dev/WHMCS-Mollie#30]
Hallo, 

After update i have this error:

Aanroepen webhook mislukt met statuscode 500 (Got HTTP/1.1 500 Internal Server Error instead of 20x)
10 januari 2018 om 16:38

M.v.g

**Comment by Josvdwoude** [comment]
Ik ondervind net het zelfde probleem, hier wat meer toegelicht.

**Betreft: Mollie iDeal**
Na bestelling/betaling in test environment.. verwijst Mollie dus naar de invoice van de klant na het zogenaamd betalen. Hier blijft hij rechtsboven in de invoice oneindig lang laden (ook nog na een halfuur), zie afbeelding.

In de test omgeving van Mollie komt wel betaald te staan.., maar dus ook de melding:
aanroepen webhook mislukt met statuscode 500.......... ondanks dit staat er wel betaald bij..
Zie afbeelding.

Maar in WHMCS zijn de facturen niet betaald, dit zelfde gebeurt ook weer na het openen van een betaling via het Clientpanel. 

Hoop dat je eruit komt!

Groetjes!

![oneindig_lang_laden_invoice](https://user-images.githubusercontent.com/12976883/35061033-45e08c3e-fbc0-11e7-9d10-821d240f135d.png)
![mollie_aanroepen_webhook_mislukt](https://user-images.githubusercontent.com/12976883/35061032-45c7fbe2-fbc0-11e7-85d6-8779a708a5a1.png)

**Comment by Wouter0100** [comment]
Damn - heeft met de naamswijziging uit #15. De callback gaat er vanuit dat hij "ideal" heet. Beetje jammer.. Ik zou aanraden even te downgraden totdat d'r een fix is.

**Comment by digiexpert** [comment]
Waar halen we de versie terug vandaan?

**Comment by Wouter0100** [comment]
[https://github.com/0100Dev/WHMCS-Mollie/releases](Hier).

**Comment by ExchequerNL** [comment]
Ik merk dat transactie ID's wegvallen sinds de update. Heeft dit hier ook mee te maken of is dat een aparte bug?

**Comment by Wouter0100** [comment]
1.0 werkt als het goed is nog wel gewoon. Is al een tijdje geleden. :+1:

**Comment by ExchequerNL** [comment]
Ik heb een backup teruggezet van de laatste versie van vóór de grote update en ik merk dat die ook niet meer werkt. Wat ik niet heb vervangen is de map vendor, die ik tijdens de 1.1 release ook heb geupdate. Het zou dus best eens kunnen dat het probleem in de update van de codes in de map vendor zit.

**Comment by ExchequerNL** [comment]
Update: Ik moest even alles uitschakelen (disable gateway) en daarna ging de pre-1.1 versie weer als vanouds.

**Comment by digiexpert** [comment]
Is het al bekend wanneer er hier een update voor komt?

**Comment by digiexpert** [comment]
Hopelijk is er al wat bekend?

**Comment by Wouter0100** [comment]
Helaas heb ik hier zelf nog geen tijd voor gehad. Erg hectische periode van verschillende splitsingen. Zo is 0100Dev nu terug bij de oorsprong: een development bedrijf, wat gelukkig goed loopt - maar hiervoor even wat minder.

Hoop er z.s.m. naar te kunnen kijken, maar for the time being zet ik hem even op help wanted.

**Comment by qarizma** [comment]
@Josvdwoude kun je mij de logs geven mbt die error 500?

**Comment by Wouter0100** [comment]
@qarizma deze error word veroorzaakt door [deze](https://github.com/0100Dev/WHMCS-Mollie/blob/6a3c0eb5f32403443f2fa6b88cb121fabeac804d/src/mollie/callback.php#L32) regel, vermoed ik. Hier zoekt hij `mollieideal` op, maar kan hij niet vinden omdat ze gerenamed is naar `mollieideal_devapp` i.v.m. de upgrade incomatibiliteit uit issue #15.

**Comment by Wouter0100** [comment]
Dat zal zorgen voor `mollieideal_devappideal`, wat ook niet echt werkt. Alleen voor ideal moet hij _devapp erachter krijgen. 

Alhoewel - bedenk ik me net dat we dan allicht het beste alles kunnen renamen naar _devapp. Zo zit een vendor er in en sluiten we ook toekomstige problemen uit - en dan kan je er simpelweg 

```php 
$_GATEWAY = getGatewayVariables('mollie' . $transaction['method'] . '_devapp');
```

van maken :-)

**Comment by qarizma** [comment]
Je hebt gelijk, ik zit helemaal niet op te letten...multitasken is niet mijn ding 😄 

Ik zal als ik het red vanavond alles renamen. Heb mijn comment aangepast.

**Comment by qarizma** [comment]
@thehosting4you @Josvdwoude @digiexpert @ExchequerNL 

Het zou fijn zijn dat jullie ook na het melden van problemen ons ondersteunen bij het verhelpen van problemen, vooral bij deze module die gratis beschikbaar is. Tot nu toe wordt er alleen maar geklaagd maar zie ik bij geen enkele issue enige vorm van support.

**Comment by ExchequerNL** [comment]
@qarizma 
Ik had eerlijk gezegd niet verwacht dat het renamen 6+ maanden zou duren. De (betaalde) mollie recurring werkt namelijk wel. De uitdaging van het hernoemen is mij niet duidelijk, maar ik ben dan ook geen programmeur (en ook geen contributor).

Wat ik wel kan doen is een WHMCS test licentie voor je regelen. Indien je daar iets mee kunt stuur dan gerust een DM.

**Comment by qarizma** [comment]
@Wouter0100 close.

**Comment by Wouter0100** [comment]
@ExchequerNL het is meer dat het tijd kost goed te doen en goed te testen. De tijd die aan deze module besteed wordt krijgen we niet betaald, en dus gaan betaalde projecten voor. Zodoende werkt Mollie Recurring gateway wel zoals het zou moeten - en is deze Mollie gateway voornamelijk afhankelijk van mijn vrije tijd of die van andere code contributors zoals @qarizma (waarvoor dank!).

Voor nu sluit ik het issue, omdat het dus werkt.
