### ISSUE TITLE
iDeal removed

### ISSUE THREAD

**Issue by qarizma** [0100Dev/WHMCS-Mollie#34]
iDeal is uit de laatste versie gehaald, vreemde keuze vind ik zelf.

`Breaks iDeal! Pak V1.0 voor een werkende iDeal module.`

Deze moet hernoemd worden om conflicten met WHMCS te vermijden. Op dit moment wordt ideal.php elke keer overschreven met een update van WHMCS.

**Comment by Wouter0100** [comment]
iDeal is niet removed, maar gerenamed zoals vele verzochten. Alleen hier kwamen issues mee, zodoende dat ik dat zinnetje er bij gezet heb.
