### ISSUE TITLE
iDEAL massapay werkt niet

### ISSUE THREAD

**Issue by JEEBEE123** [0100Dev/WHMCS-Mollie#36]
De iDEAL functie werkt niet goed bij het gebruik van de massapayfunctie. Zie https://s.amsu.ng/B3mq9u4OEqIN (sorry voor de achtergrondherrie, iets met buitenland, hotel en hangjeugd... ;)

En zie foto: Deze melding blijft (indien de betaling wordt afgebroken) continu verschijnen en het scherm blijft verversen.
![untitled](https://user-images.githubusercontent.com/38722343/39241475-60a126b2-48ca-11e8-9059-0c8bfd83415c.png)

**Comment by Wouter0100** [comment]
Check even 2.0 of dat werkt.

**Comment by Wouter0100** [comment]
Ik ga er dan even vanuit dat het werkt (gezien het hier in dev omgeving ook prima werkt). Zo niet, kan je gewoon weer openen!
