### ISSUE TITLE
Aanroepen webhook mislukt met statuscode 500 (Got HTTP/1.1 500 Internal Server Error instead of 20x)

### ISSUE THREAD

**Issue by JEEBEE123** [0100Dev/WHMCS-Mollie#37]
Na een succesvolle betaling wordt dit niet aan WHMCS doorgegeven.

Mollie geeft aan:
Aanroepen webhook mislukt met statuscode 500 (Got HTTP/1.1 500 Internal Server Error instead of 20x)

PHP 7.2.4 en nieuwste WHMCS update.

**Comment by JEEBEE123** [comment]
Nevermind..

Ik moet wat verder kijken dan mij neus lang is.

Probleem verholpen door regel 32 in callback.php te veranderen van..

`$_GATEWAY = getGatewayVariables('mollie' . $transaction['method']);`

naar

`$_GATEWAY = getGatewayVariables('mollie' . $transaction['method'] . '_devapp');`

Zoals eerder omschreven :)

**Comment by Wouter0100** [comment]
Goed te horen. WErkt #35 anders?

**Comment by JEEBEE123** [comment]
Krijg helaas de foutmelding weer opnieuw. Er is verder niks veranderd. Wat te doen?

**Comment by JEEBEE123** [comment]
Heb #35 geprobeerd, helaas geen geluk. iDEAL werkt wel, PayPal niet.

Aanroepen webhook mislukt met statuscode 500 (Got HTTP/1.1 500 Internal Server Error instead of 20x)
