### ISSUE TITLE
kan niet instaleren

### ISSUE THREAD

**Issue by spike1984** [0100Dev/WHMCS-Mollie#4]
goedendag Wouter
ik heb een linux server en de code van jou werkt der niet op 
ik heb het al bestandje voor bestandje zelf in mij whmcs gekopieerd 
maar dat werkt ook niet heb allen ideal en de andere dingen niet en die andere wil ik juist hebben 
kan u me helpen der bij ?

met vriendelijk groet martin

**Comment by Wouter0100** [comment]
Het voorbeeld commando is voor een Linux server, het werkt daar eigenlijk altijd wel op. Wat krijg je precies voor een error? Helemaal niks?

**Comment by spike1984** [comment]
/var/www/vhosts/zinglo.net/httpdocs$ git clone --recursive https://github.com/0100Dev/WHMCS-Mollie.git /tmp/whmcs && sudo mv /tmp/whmcs/src ./modules/gateways/
-bash: regel 7: git: opdracht niet gevonden

dit is wat de winscp zecht

**Comment by Wouter0100** [comment]
winscp is volgensmij FTP? Dit commando via SSH uitgevoerd worden. 

Probeer anders [deze](https://github.com/0100Dev/WHMCS-Mollie/releases/download/v1.0/whmcs-mollie.tar.gz) release.

**Comment by spike1984** [comment]
winscp is een ftp met ssh in geboud en ik ook via putty gebrobeert maar dan vind ik me map van whmcs niet eens :( 

en nu ik die zit van jou bekeken en der zijn hoop mappen die ik niet kan vinden :(

**Comment by Wouter0100** [comment]
Kan je wat duidelijker zijn in je antwoorden, welke mappen zie je bijv. niet en waardoor weet je dat hij je WHMCS map niet vind?

**Comment by spike1984** [comment]
moet ik de .git map ook verplaatsen ergens in ?

de module werkt nu half heb de modules aan die ik wil gebruiken 
maar als je dan wil betalen dan krijg je een fout pagina een serverfout 500

**Comment by Wouter0100** [comment]
Dat is uiteraard niet de bedoeling. De `.git` map is niet nodig, alhoewel het wel aan te raden is. Daarmee kan je straks makkelijk upgraden naar een laatste versie.

Welke error krijg je precies? Staan er fouten in de error logs? Zet anders even in WHMCS's settings onder "General Settings" => "Other" => Display Errors aan, dan worden alle errors op je scherm weergegeven en kan je deze naar mij toesturen.

**Comment by Wouter0100** [comment]
Kijk anders ook even of het zelfde bij #5 zich hier niet voordoet.

**Comment by spike1984** [comment]
ik kan nu helemala niks meer bij die error die ik kreeg server 500 error 
ben ik gaan kijken wat het was en kwam ik achter ik dus niet meer in me server kon inloggen en nu licht me heledatabase plat 
dus ik brobeer te redden wat ik kan redden en een herinstal op de server doen 
en dan denk ik dat ik jou vraag om het te instaleren want mij lukt het echt niet ik sloop alleen maar alles blijk baar :(

**Comment by spike1984** [comment]
nou server is helemaal naar de klote kan nergens meer bij de mysql is weg of zo 
dis de error ik nu krijg 
ERROR: PleskDBException: Unable to connect to database: mysql_connect(): No such file or directory (Error code: 2002) (Abstract.php:69)

Search for related Knowledge Base articles

kan echt helemaal niks meer :( 
dus ja bedankt voor het broberen van helpen van mij 

misschien als jij weet we dit kunne oplossen zonder iets anders kwijd te raken wand elke keer als ik server onieuwe instaler en de backup terug zet maak niet uit of ik die van gisteren doe of van 3 weekn terug het werkt niet meer :(

**Comment by Wouter0100** [comment]
Dat zijn problemen die niet met deze plugin te maken hebben. Ook zullen de instructies die staan vermeld niet naar dit soort problemen lijden.. Ik sluit hierbij dit issue, als je nog met een fout/bug komt van deze gateway kan je een nieuwe issue aanmaken.
