### ISSUE TITLE
WHMCS 7.5.0 Mollie

### ISSUE THREAD

**Issue by imadlatch** [0100Dev/WHMCS-Mollie#45]
latest release TESTED on 7.5.0 
result :-1: 
Oops! Something went wrong and we couldn't process your request.
Any fix on that version ?

Kind Regards

**Comment by Wouter0100** [comment]
Unfortunate to hear that the gateway didn't work. We've also tested it on 7.5 where it works flawless. 

Please open an issue with more detailed information or contact us at support@0100dev.nl for business support.

**Comment by imadlatch** [comment]
It is working fine on WHMCS 7.6.1 I just updated.
Do you offer Tokenized Version ? I would buy it
great job Thanks.
