### ISSUE TITLE
Error at WHMCS with PHP-7.3

### ISSUE THREAD

**Issue by Noahkemm** [0100Dev/WHMCS-Mollie#48]
`[Tue Mar 12 17:19:38.833955 2019] [php7:error] [pid 17740] [client 91.218.66.10:61104] PHP Fatal error:  require_once(): Failed opening required '/var/www/panel/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/panel/modules/gateways/mollie/mollie.php on line 3, referer: https://panel.mykns.net/admin/configaddonmods.php
[Tue Mar 12 17:19:38.835838 2019] [php7:notice] [pid 17740] [client 91.218.66.10:61104] [WHMCS Application] ERROR: Whoops\\Exception\\ErrorException: require_once(): Failed opening required '/var/www/panel/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/panel/modules/gateways/mollie/mollie.php:3 Stack trace: #0 /var/www/panel/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\\Utility\\Error\\Run->handleError(64, 'require_once():...', '/var/www/panel/...', 3) #1 [internal function]: WHMCS\\Utility\\Error\\Run->handleShutdown() #2 {main} {"exception":"[object] (Whoops\\\\Exception\\\\ErrorException(code: 64): require_once(): Failed opening required '/var/www/panel/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/usr/share/php') at /var/www/panel/modules/gateways/mollie/mollie.php:3)"} [], referer: https://panel.mykns.net/admin/configaddonmods.php
`

**Comment by thomashoeky** [comment]
This seems to be more of a missing file issue it seems
>Failed opening required '/var/www/panel/modules/gateways/mollie/vendor/autoload.php'

**Comment by Wouter0100** [comment]
Read readme. You're missing a critical step.
