### ISSUE TITLE
Hoe werkt de handmatige installatie?

### ISSUE THREAD

**Issue by mausav** [0100Dev/WHMCS-Mollie#5]
Ik heb de module gedownload. Ik krijg dan in feite de volgende structuur:

Dir. mollie
 - map lang
 - map vendor
 - 3 bestanden in de map mollie

in de root bevinden zich de betalingsmgelijkheden php bestanden.

Dus de php bestanden worden geupload naar de root map van whmcs namelijk ..modules\gateway

De map mollie kom dan ook in deze dir. te staan. Als ik nu naar WHMCS ga naar "setup" en dan "betalingen"  en dan "betaling gateways" dan krijg ik een error 500. Haal ik dan de php bestanden uit de map modules\gateway dan werkt de optie "betaling gateways" prima.

Plaats ik dan iets verkeerd?

**Comment by Wouter0100** [comment]
Vervelend te horen dat je dit soort problemen ervaart. Alles uit de `src` folder moet in WHMCS's `\modules\gateways` folder. Als je even onder "General Settings" => "Other" en dan Display Errors aanzet, zie je wat de 500 error is op de Gateway Payments pagina.

**Comment by mausav** [comment]
Fatal error: require_once(): Failed opening required '/home/admin/domains/mijndomeinnaam.nl/public_html/order/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Autoloader.php' (include_path='/home/admin/domains/mijndomeinnaam.nl/public_html/order/vendor/phpseclib/phpseclib/phpseclib:.:/usr/local/php54/lib/php') in /home/admin/domains/mijndomeinnaam.nl/public_html/order/modules/gateways/mollie/mollie.php on line 3

**Comment by Wouter0100** [comment]
Die error is vreemd. In de folder `/home/admin/domains/mijndomeinnaam.nl/public_html/order/modules/gateways/mollie/vendor/` zit toch wel een folder met `Mollie`? Zo niet heb je
* of; het "installatie"-commando in de `README.md` niet juist uitgevoerd.
* of; niet de juiste files gedownload uit de release, namelijk [deze](https://github.com/0100Dev/WHMCS-Mollie/releases/download/v1.0/whmcs-mollie.tar.gz).

**Comment by mausav** [comment]
Ah kijk dat was het probleem :)
Bedankt voor je snelle hulp!

**Comment by Wouter0100** [comment]
Fijn te horen! Ik heb om het wat duidelijker te maken ook FTP instructies toegevoegd aan de `README.md` in 42b183d409a03710c25483747053de374b3952e5.
