### ISSUE TITLE
Missing button translation for Przelewy24

### ISSUE THREAD

**Issue by 040hosting** [0100Dev/WHMCS-Mollie#51]
missing in /mollie/lang/dutch.php

`$_GATEWAYLANG['payWithPrzelewy24'] = 'Betaal met Przelewy24';`

missing in /mollie/lang/english.php

`$_GATEWAYLANG['payWithPrzelewy24'] = 'Pay with Przelewy24';`

otherwise the payment button stays empty.

**Comment by Wouter0100** [comment]
Available in latest release.
