### ISSUE TITLE
mollie betalingsstatus blijft open staan

### ISSUE THREAD

**Issue by roxgoesforkika** [0100Dev/WHMCS-Mollie#52]
Mijn betalingssysteem werkt sinds vorig jaar prima, sinds 19 mei komen de betalingen wel binnen bij Mollie (ik ontvang wel het geld) maar de status op wordpress blijft op Open staan. Hierdoor voert hij een aantal acties niet uit die pas geactiveerd worden  zodra de status op wordpress op betaald staat. Ik krijg via mollie wel de betalingsbevestiging binnen en het geld wordt wel overgemaakt. Alleen op de website blijven alle betalingen op open staan.

**Comment by thomashoeky** [comment]
Dit is de Mollie plugin voor WHMCS, niet voor Wordpress. Je kan het beste contact opnemen met de plugin maker van de plugin die je gebruikt
