### ISSUE TITLE
mollie betalingsstatus wordt niet geupdate

### ISSUE THREAD

**Issue by msngod** [0100Dev/WHMCS-Mollie#54]
Hi Wouter,
Ik heb de WHMCS mollie plugin geinstalleerd en bij het kiezen van een iDeal betaling kom ik netjes op de webpagina van de bank en wordt de transactie vanuit de bank met success afgerond en komt de betaling binnen bij Mollie en ik krijg netjes een mailtje van mollie dat de betaling is ontvangen maar de status in WHMCS blijft op Open staan. Ik wordt netjes vanuit de bank terug gestuurd naar WHMCS waarna WHMCS de status bij mollie probeert op te halen, maar dit blijft in het oneindig doorgaan en is op te merken doordat de pagina wordt gefreshed.

Heb jij hier een oplossing voor?

**Comment by tamerciaga** [comment]
Welke versie van WHMCS gebruik je?
Wat staat erbij Webhook URL in je transactie in je Mollie dashboard?

**Comment by Wouter0100** [comment]
Misschien trouwens duplicate van #53?

**Comment by msngod** [comment]
> 
> 
> Welke versie van WHMCS gebruik je?
> Wat staat erbij Webhook URL in je transactie in je Mollie dashboard?

Dank je wel voor je reactie @tamerciaga!

Ik gebruik Version: 7.7.1 van WHMCS en mijn webhook URL is:

https://portal.XXXXXX.com/modules/gateways/mollie/callback.php

**Comment by tamerciaga** [comment]
Staat er in de logs ook iets zoals: "Webhook met succes aangeroepen, duurde 0,3 seconden"
Is die URL ook buiten je netwerk te bereiken (door Mollie)?

Vreemd probleem, aangezien ik er met 3 bedrijven mee werk zonder problemen.
@Wouter0100 denk het niet, dat andere issue gaat over een missing slash. Deze webhook URL lijkt goed te zijn.

**Comment by msngod** [comment]
@tamerciaga 
Nee helaas niks in de log is het volgende te zien. Ik heb een screenshot toegevoegd van de logging.
<img width="125" alt="Capture" src="https://user-images.githubusercontent.com/51704829/59687262-135a5d80-91dd-11e9-9a94-5bb7aa669bce.PNG">

@Wouter0100 
Deze post kwam ik ook tegen en de / had ik al aangepast in het .php bestand, maar dit heeft voor mij nog niet gewerkt.

**Comment by thomashoeky** [comment]
Gaat zo te zien toch iets fout in je website, die redirect de webhook URL. Kun je zelf wel naar die webhook URL toe?
> https://portal.XXXXXX.com/modules/gateways/mollie/callback.php

**Comment by msngod** [comment]
@thomashoeky,

Dank je voor je reactie!
Ik krijg inderdaad een 404
<img width="599" alt="404" src="https://user-images.githubusercontent.com/51704829/59689017-2110e280-91df-11e9-9a2c-5b0f660519ae.PNG">

**Comment by thomashoeky** [comment]
Bestaat het bestand verder wel op je hostingpakket? Dan gaat er gok ik iets mis in je htaccess, of ergens anders iets. Bij mij geeft die pagina op mijn eigen site een 500 (gok dat dit normaal is omdat het verder geen callback van mollie is)

**Comment by Wouter0100** [comment]
@thomashoeky 500 is normaal. Vroeger waren dit 404 e.d., maar dat gaf verwarring in dit soort scenario's. Zie [hier](https://github.com/0100Dev/WHMCS-Mollie/blob/master/src/mollie/callback.php). Wss krijg je een `500 Arg mismatch`.

@msngod lijkt inderdaad wat fout te zijn in je htaccess. Mollie geeft ook aan dat er redirects plaatsvinden. Dit hoort niet.

**Comment by msngod** [comment]
Ik heb het even getest en heb hierbij de .htaccess file verwijderd en nu kan ik inderdaad callback.php bereiken en ik krijg ook een 500 error.

Ik heb daarna een betaling gedaan via iDEAL maar krijg nog steeds hetzelfde resultaat dat WHMCS de pagina blijft refreshen.
Bij mollie zie ik het volgende:
<img width="224" alt="error" src="https://user-images.githubusercontent.com/51704829/59691008-a8ac2080-91e2-11e9-8156-179621fdccfa.PNG">

**Comment by msngod** [comment]
En de webhook URL is, volgens de WHMCS loggin:

https://portal.XXXX.com/modules/gateways/mollie/callback.php

**Comment by tamerciaga** [comment]
Het probleem staat echt uitgelegd in je screenshot, wij kunnen hier geen hulp bieden omtrent server administratie.

**Comment by thomashoeky** [comment]
Zet anders je error logging aan, dan kan je kijken wat de 500 error inhoud. Met de mollie callback hoor je namelijk geen 500 error te krijgen

**Comment by msngod** [comment]
Het probleem is opgelost.

De volgende error melding was in de log te vinden:
[Tue Jun 18 19:07:53.320852 2019] [:error] [pid 3244208:tid 47915605182208] [client XX.XX.XX:57976] SoftException in Application.cpp:261: File "/home/***/public_html/portal.***.com/modules/gateways/mollie/callback.php" is writeable by group

De rechten op de files en folder waren 644 op files en 755 op folders, maar de hostingpartij moest op hun servers de rechten goed zetten, waardoor alles nu werkt. 
Nu zijn er ook geen aanpassingen aan het .htaccess file nodig.
