### ISSUE TITLE
Fout in whmcs 7.7 cron na updaten plugin

### ISSUE THREAD

**Issue by ExchequerNL** [0100Dev/WHMCS-Mollie#57]
Ik ben van de 1.x plugin naar de laatste officiele release gegaan (2.8 van 27 mei) en sinds dat moment krijg ik elke dag een error report binnen van de dagelijkse WHMCS cron.

WHMCS geeft aan dat de cron de laatste 24 uur niet succesvol is verlopen.

Volgende rapport stuurt directadmin na het aanroepen van de cron:

`[WHMCS Application] ERROR: TypeError: Argument 1 passed to GuzzleHttp\Ring\Client\StreamHandler::__invoke() must be of the type array, object given, called in /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php on line 277 and defined in /home/user/domains/my.x.com/public_html/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26 Stack trace: #0 /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\Ring\Client\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #1 /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #2 /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array) #3 /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', 'https://pki.whm...', Array) #4 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): GuzzleHttp\Client->__call('get', Array) #5 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getUrl('https://pki.whm...') #6 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getPathFromKeyserver('certs.json') #7 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getCertMetadata() #8 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->reloadCrls() #9 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getCrlForCertificate(Object(WHMCS\Installer\Composer\Certificate)) #10 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->validateCertificateNotRevoked(Object(WHMCS\Installer\Composer\Certificate)) #11 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getTrustedCertificate('515FCBEB9958DA4...', 2) #12 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->validateCertificateSignatureIsTrusted(Object(WHMCS\Installer\Composer\Certificate)) #13 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getTrustedCertificate('0C12A820D7DD9ED...', 1) #14 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/PackagesFile.php(0): WHMCS\Installer\Composer\CertificateManager->getValidCodeSigningCertificateContent('0C12A820D7DD9ED...') #15 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/WhmcsRepository.php(0): WHMCS\Installer\Composer\PackagesFile->validateNotificationSignatures(Array) #16 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(462): WHMCS\Installer\Composer\WhmcsRepository->fetchFile('https://release...', 'UpdatePackagesD...') #17 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(256): Composer\Repository\ComposerRepository->loadRootServerFile() #18 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/DependencyResolver/Pool.php(99): Composer\Repository\ComposerRepository->hasProviders() #19 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Installer.php(402): Composer\DependencyResolver\Pool->addRepository(Object(WHMCS\Installer\Composer\WhmcsRepository), Array) #20 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Installer.php(228): Composer\Installer->doInstall(Object(Composer\Repository\InstalledArrayRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array, false) #21 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(173): Composer\Installer->run() #22 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Command/Command.php(259): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #23 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #24 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/WhmcsComposerApplication.php(0): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #25 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(192): WHMCS\Installer\Composer\WhmcsComposerApplication->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #26 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Console/Application.php(189): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #27 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #28 /home/user/domains/my.x.com/public_html/vendor/composer/composer/src/Composer/Console/Application.php(99): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #29 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerWrapper.php(0): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #30 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerWrapper.php(0): WHMCS\Installer\Composer\ComposerWrapper->update() #31 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerWrapper->getLatestVersion() #32 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerUpdate->WHMCS\Installer\Composer\{closure}() #33 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerUpdate->doComposerCommand(Object(Closure)) #34 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Installer/Update/Updater.php(0): WHMCS\Installer\Composer\ComposerUpdate->getLatestVersion(true) #35 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/CheckForWhmcsUpdate.php(0): WHMCS\Installer\Update\Updater->fetchComposerLatestVersion() #36 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\CheckForWhmcsUpdate->__invoke() #37 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #38 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #39 /home/user/domains/my.x.com/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) #40 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 /home/user/domains/my.x.com/public_html/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 /home/user/domains/my.x.com/public_html/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #45 {main} {"exception":"[object] (TypeError(code: 0): Argument 1 passed to GuzzleHttp\\Ring\\Client\\StreamHandler::__invoke() must be of the type array, object given, called in /home/user/domains/my.x.com/public_html/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php on line 277 at /home/user/domains/my.x.com/public_html/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26)"} [] <!DOCTYPE html> <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oops!</title>
    
<style>
        body {
            margin: 30px 40px;
            background-color: #f6f6f6;
        }
        .error-container {
            padding: 50px 40px;
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 14px;
        }
        h1 {
            margin: 0;
            font-size: 48px;
            font-weight: 400;
        }
        h2 {
            margin: 0;
            font-size: 26px;
            font-weight: 300;
        }
        a {
            color: #336699;
        }
        p.back-to-home {
            margin-top: 30px;
        }
        p.debug{
            padding: 20px 0;
            font-family: "Courier New", Courier, monospace, serif;
            font-size: 14px;
        }
        .info {
            border: solid 1px #999;
            padding: 5px;
            background-color: #d9edf7;
        }
    </style>

  </head>
  <body>
    <div class="error-container">
<h1>Oops!</h1>
<h2>Something went wrong and we couldn't process your request.</h2> <p>Please go back to the previous page and try again.</p> </div>
  </body>
</html>
`

Meer mensen met dit probleem?

**Comment by Wouter0100** [comment]
Duplicate van #47 lijkt het op? :)
