### ISSUE TITLE
Payment Gateway pagina in WHMCS stuk

### ISSUE THREAD

**Issue by Dylanvv** [0100Dev/WHMCS-Mollie#9]
Na het plaatsen van de bestanden via de FTP in de Gateway folder van WHMCS is het niet meer mogelijk om de Payment Gateway pagina in WHMCS te benaderen. Er volgt een 500 error.

**Comment by Wouter0100** [comment]
Welke 500 error krijg je precies? Kan je Display Errors in General Settings => Other even aanzetten?

**Comment by digiexpert** [comment]
Hier hetzelfde probleem

**Comment by Wouter0100** [comment]
Hetzelfde voor zou ik aan jou willen vragen, @digiexpert. Meer informatie is nodig om het probleem op te kunnen lossen.

**Comment by digiexpert** [comment]
Fatal error: Cannot redeclare mollieideal_config() (previously declared in /home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollieideal2.php:0) in /home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollieideal.php on line 16

**Comment by Wouter0100** [comment]
Verwijder `mollieideal2.php`.

**Comment by digiexpert** [comment]
Fatal error: require_once(): Failed opening required '/home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Autoloader.php' (include_path='/home/digi/domains/digi-expert.nl/private_html/client/vendor/phpseclib/phpseclib/phpseclib:.:/usr/local/lib/php') in /home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollie/mollie.php on line 3

**Comment by Wouter0100** [comment]
Je installatie is niet goed gegaan. Doorloop de installatie stappen even opnieuw en zorg dat je niks mist.

**Comment by digiexpert** [comment]
Ik heb het via ftp gedaan. Blijf die melding houden

**Comment by Wouter0100** [comment]
Bestaat de file `/home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollie/vendor/Mollie/src/Mollie/API/Autoloader.php`?

**Comment by digiexpert** [comment]
Ik heb de fout gevonden
Als je de zip hebt, dan is de inhoud in /home/digi/domains/digi-expert.nl/private_html/client/modules/gateways/mollie/vendor/Mollie/src/Mollie/

daar is het leeg

**Comment by digiexpert** [comment]
Deze zit ook niet in de zip

**Comment by Wouter0100** [comment]
Lees de documentatie nog even overnieuw. Je moet de `whmcs-mollie.tar.gz` downloaden (oftewel, van [deze](https://github.com/0100Dev/WHMCS-Mollie/releases) pagina [deze](https://github.com/0100Dev/WHMCS-Mollie/releases/download/v1.0/whmcs-mollie.tar.gz) (v1.0) link), niet de `Source code (zip)` of `Source code (tar.gz)`. Deze zijn inderdaad incompleet, wat we helaas niet kunnen aanpassen. Dit is een automatisch dingetje van Github.

**Comment by digiexpert** [comment]
Werkt
